<a href="https://colab.research.google.com/github/NinjaBlac/business-analytics-assignments/blob/main/Transition_States_Case_Study_3_Assignment_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question One

Student Attendance Transition Matrix -

                Present    Late    Absent

    Present     20/27      5/27      2/27

    Late        8/21       10/21     3/21

    Absent      5/21       1/21      15/21

In [ ]:
import numpy as np

# Define the transition matrix
transition_matrix = np.array([
    [20/27, 5/27, 2/27],  # Present
    [8/21, 10/21, 3/21],  # Late
    [5/21, 1/21, 15/21]   # Absent
])

print(transition_matrix)

[[0.74074074 0.18518519 0.07407407]
 [0.38095238 0.47619048 0.14285714]
 [0.23809524 0.04761905 0.71428571]]


In [ ]:
current_state = np.array([1, 0, 0]) #Present
outcomes = ["Present", "Late", "Absent"]

In [ ]:
print("Current state:", outcomes[np.argmax(current_state)])

Current state: Present


## Probability of 9 Pairs

In [ ]:

# Define the state pairs to calculate probabilities for
state_pairs = [
    ("Present", "Present"),
    ("Present", "Late"),
    ("Present", "Absent"),
    ("Late", "Present"),
    ("Late", "Late"),
    ("Late", "Absent"),
    ("Absent", "Present"),
    ("Absent", "Late"),
    ("Absent", "Absent")
]

# Calculate and print the probabilities
for pair in state_pairs:
    from_state = pair[0]
    to_state = pair[1]
    from_index = outcomes.index(from_state)
    to_index = outcomes.index(to_state)
    probability = transition_matrix[from_index, to_index]
    print(f"Probability of transitioning from {from_state} to {to_state}: {probability}")


Probability of transitioning from Present to Present: 0.7407407407407407
Probability of transitioning from Present to Late: 0.18518518518518517
Probability of transitioning from Present to Absent: 0.07407407407407407
Probability of transitioning from Late to Present: 0.38095238095238093
Probability of transitioning from Late to Late: 0.47619047619047616
Probability of transitioning from Late to Absent: 0.14285714285714285
Probability of transitioning from Absent to Present: 0.23809523809523808
Probability of transitioning from Absent to Late: 0.047619047619047616
Probability of transitioning from Absent to Absent: 0.7142857142857143


# Question 2

## Probability of Late to Absent

In [ ]:
# Probability of transitioning from late to absent (P_LA)
P_LA = transition_matrix[1, 2]

print(f"Probability of transitioning from late to absent (P_LA): {P_LA}")


Probability of transitioning from late to absent (P_LA): 0.14285714285714285


## Probability that it will be Present The Next Day (Present to Present)

In [ ]:
current = np.array([1, 0, 0]) #Present

# Compute the state distribution after one day
state_distribution_after_one_day = np.dot(current_state, np.linalg.matrix_power(transition_matrix, 1))

# Extract the probability of being in the "present" state after 1 day
# Assuming "present" corresponds to the first state (index 0)
prob_present_after_one_day = state_distribution_after_one_day[0]

print("Probability of being in the 'present' state after one day:", prob_present_after_one_day)


Probability of being in the 'present' state after one day: 0.7407407407407407


## Probability of Being Absent After 21 Days (Late to Absent)

In [ ]:
current_state = np.array([0, 1, 0]) #Late
# Compute the state distribution after 21 days
state_distribution_after_twenty_one_days = np.dot(current_state, np.linalg.matrix_power(transition_matrix, 21))

# Extract the probability of being in the "absent" state after 21 days
# Assuming "absent" corresponds to the third state (index 2)
prob_absent_after_twenty_one_days = state_distribution_after_twenty_one_days[2]

print("Probability of being in the 'absent' state after twenty one days:", prob_absent_after_twenty_one_days)

Probability of being in the 'absent' state after twenty one days: 0.24666396442273023


## Probability of Being Present After 3 Days (Late to Present)

In [ ]:
current_state = np.array([0, 1, 0]) #Late

# Compute the state distribution after 3 days
state_distribution_after_three_days = np.dot(current_state, np.linalg.matrix_power(transition_matrix, 3))

# Extract the probability of being in the "absent" state after 3 days
# Assuming "present" corresponds to the third state (index 2)
prob_present_after_three_days = state_distribution_after_three_days[0]

print("Probability of being in the 'present' state after three days:", prob_present_after_three_days)

Probability of being in the 'present' state after three days: 0.5316587148282789


## Probability of Being Present After 10 Days ( Absent to Present)

In [ ]:
current_state = np.array([0, 0, 1]) #Absent

# Compute the state distribution after 10 days
state_distribution_after_ten_days = np.dot(current_state, np.linalg.matrix_power(transition_matrix, 10))

# Extract the probability of being in the "present" state after 10 days
# Assuming "present" corresponds to the third state (index 2)
prob_present_after_ten_days = state_distribution_after_ten_days[0]

print("Probability of being in the 'present' state after ten days:", prob_present_after_ten_days)

Probability of being in the 'present' state after ten days: 0.5367996629548141


# Question 3

In [ ]:
state_pairs = [ ("Present", "Absent"), ("Absent", "Present"),("Late", "Present"),("Late", "Absent")]

## Present to Absent

In [ ]:
# Define the initial state starting from "Present"
current_state = np.array([1, 0, 0])  # Starting from "Present"

# Define the target state index for "Absent"
target_state_index = outcomes.index("Absent")

# Simulate the process for 27 days or until "Absent" is reached
day = 1
max_days = 27

while np.argmax(current_state) != target_state_index and day <= max_days:
    current_state = np.dot(current_state, transition_matrix)
    print(f"Day {day}: {outcomes[np.argmax(current_state)]}")
    day += 1

if np.argmax(current_state) == target_state_index:
    print(f"Transition completed from Present to Absent in {day-1} days.")
else:
    print("Transition to Absent did not occur within 27 days.")

Day 1: Present
Day 2: Present
Day 3: Present
Day 4: Present
Day 5: Present
Day 6: Present
Day 7: Present
Day 8: Present
Day 9: Present
Day 10: Present
Day 11: Present
Day 12: Present
Day 13: Present
Day 14: Present
Day 15: Present
Day 16: Present
Day 17: Present
Day 18: Present
Day 19: Present
Day 20: Present
Day 21: Present
Day 22: Present
Day 23: Present
Day 24: Present
Day 25: Present
Day 26: Present
Day 27: Present
Transition to Absent did not occur within 27 days.


## Absent to Present

In [ ]:
# Define the initial state starting from "Absent"
current_state = np.array([0, 0, 1])  # Starting from "Absent"

# Define the target state index for "Present"
target_state_index = outcomes.index("Present")

# Simulate the process for 27 days or until "Present" is reached
day = 1
max_days = 27

while np.argmax(current_state) != target_state_index and day <= max_days:
    current_state = np.dot(current_state, transition_matrix)
    print(f"Day {day}: {outcomes[np.argmax(current_state)]}")
    day += 1

if np.argmax(current_state) == target_state_index:
    print(f"Transition completed from Absent to Present in {day-1} days.")
else:
    print("Transition to Present did not occur within 27 days.")

Day 1: Absent
Day 2: Absent
Day 3: Present
Transition completed from Absent to Present in 3 days.


## Late to Present

In [ ]:
# Define the initial state starting from "Late"
current_state = np.array([0, 1, 0])  # Starting from "Late"

# Define the target state index for "Present"
target_state_index = outcomes.index("Present")

# Simulate the process for 27 days or until "Present" is reached
day = 1
max_days = 27

while np.argmax(current_state) != target_state_index and day <= max_days:
    current_state = np.dot(current_state, transition_matrix)
    print(f"Day {day}: {outcomes[np.argmax(current_state)]}")
    day += 1

if np.argmax(current_state) == target_state_index:
    print(f"Transition completed from Late to Present in {day-1} days.")
else:
    print("Transition to Present did not occur within 27 days.")

Day 1: Late
Day 2: Present
Transition completed from Late to Present in 2 days.


## Late to Absent

In [ ]:
 #Define the initial state starting from "Late"
current_state = np.array([0, 1, 0])  # Starting from "Late"

# Perform the simulation to determine transition
target_state_index = outcomes.index("Absent")
day = 1
max_days = 27

while np.argmax(current_state) != target_state_index and day <= max_days:
    current_state = np.dot(current_state, transition_matrix)
    print(f"Day {day}: {outcomes[np.argmax(current_state)]}")
    day += 1

if np.argmax(current_state) == target_state_index:
    print(f"Transition completed from Late to Absent in {day-1} days.")
else:
    print("Transition to Absent did not occur within 27 days.")

Day 1: Late
Day 2: Present
Day 3: Present
Day 4: Present
Day 5: Present
Day 6: Present
Day 7: Present
Day 8: Present
Day 9: Present
Day 10: Present
Day 11: Present
Day 12: Present
Day 13: Present
Day 14: Present
Day 15: Present
Day 16: Present
Day 17: Present
Day 18: Present
Day 19: Present
Day 20: Present
Day 21: Present
Day 22: Present
Day 23: Present
Day 24: Present
Day 25: Present
Day 26: Present
Day 27: Present
Transition to Absent did not occur within 27 days.
